### ISSUE TITLE
Recherche analyste en détection d’incident

### ISSUE THREAD

**Issue by guillaumefe** [guillaumefe/megaquizz#1]
**Tâches**:
```
    - Monitoring d'un historique d'événement.
    - Présence régulière.
```

**Comment by Kaawak** [comment]
Coucou

**Comment by Kaawak** [comment]
Memo : 

- 7 décembre 17h03 ✔️ 
- 9 décembre 09h09 ✔️ 
- 10 décembre 11h02 ✔️ 
- 15 décembre 17h29 ✔️    
- 17 décembre 17h36 ✔️
- 07 janvier 09h19 ✔️
